Update training phase to reflect custom document
mindee/documentation pull request #16
Opened 2021-12-22 21:58 UTC by fakela

Update training phase to reflect custom document: add new images, links and new information to reflect new document

2021-12-23 09:56 UTC, fharper commented
Should be use other type of documents than off-the-shelf API ones for the API Builder examples? Rent receipt is still a receipt no?

2021-12-23 10:51 UTC, fakela commented
> Should be use other type of documents than off-the-shelf API ones for the API Builder examples? Rent receipt is still a receipt no?

Do you have an idea on the one I should use? Maybe Train ticket. 

Rent-receipt is still a receipt but it's kinda different because it's specifically for rent and has different fields from the average receipt. In the off-the-shelf API  i saw only expense receipt.

2022-01-03 19:18 UTC, fharper requested changes
Some more modifications for this PR :)

2022-01-03 19:18 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> +If you want to dive deeper into our product, feel free to reach out to our data scientist team: contact@mindee.com
I asked the data science team

2022-01-03 19:18 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> +3. Next, click on **Validate**. When you “validate”, you are telling the deep learning model that this blue box is the one corresponding to the date. In other words, you are **teaching the model whic
The screenshot below show reservation number as the paragraph on top, but here you mention it's corresponding to date.

2022-01-03 19:18 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> +        "https://files.readme.io/7269372-Screenshot_2021-12-24_at_09.42.59.png",
Maybe a screenshot with the mouse pointer over the validate button?

2022-01-03 19:18 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> + Without any prediction, the /predict endpoint and the training cycle looks like this:
`/predict` in code formatting

2022-01-03 19:18 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
>  The /annotations endpoint is automatically called within the interface, but you can also use the API if you want to do this on your own interface.
`/annotations` in code formatting

2022-01-03 20:10 UTC, fakela commented on build-your-first-document-parsing-api/training-interface.md
> +If you want to dive deeper into our product, feel free to reach out to our data scientist team: contact@mindee.com
we can wait for a response from them by tomorrow, or we could add contact the devrel team(email address) if they are unsure or remove completely

2022-01-04 08:15 UTC, fakela commented on build-your-first-document-parsing-api/training-interface.md
> +3. Next, click on **Validate**. When you “validate”, you are telling the deep learning model that this blue box is the one corresponding to the date. In other words, you are **teaching the model whic
I missed that

2022-01-04 19:58 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> +If you want to dive deeper into our product, feel free to reach out to our data scientist team: contact@mindee.com
They didn't respond, I say remove it.

2022-01-04 20:00 UTC, fharper commented on build-your-first-document-parsing-api/training-interface.md
> +If you want to dive deeper into our product, feel free to reach out to our data scientist team: contact@mindee.com
I removed it

2022-01-04 20:04 UTC, fharper approved these changes
LGTM

2022-01-04 20:05 UTC, merged