Review welcome to our developer portal
mindee/documentation pull request #187
Opened 2022-01-06 12:54 UTC by fakela

Review welcome to our developer portal #134

2022-01-07 00:00 UTC, fakela commented
@fharper for the off-the-shelf API I was thinking do we add the locale information on the welcome page or we link to it after have created the page.

2022-01-07 16:09 UTC, fakela commented
Need to update the definition for annotation and predictions( it needs a simpler definition)

2022-01-07 16:43 UTC, fakela commented
> Need to update the definition for annotation and predictions( it needs a simpler definition)

This is done ✅

2022-01-07 21:53 UTC, fharper requested changes

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +[Mindee](https://mindee.com) is an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer using computer vision and machine learning.
**extracting information**

This is the big difference between a regular OCR and us. An OCR, extract the information of a document: we extract key information, or predefined information from the document. We should keep the key keyword, or rephrase it so it's clear.

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- need high-quality data extracted.
*extraction ?

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +Mindee has a developer-first mindset and aims to build powerful document parsing APIs that developers can utilize to solve their problems. Mindee can be used if you are:
The following examples are good, but it's missing something about the fact that:
- you remove the human factor, so less mistakes
- you do not need manual entry, so faster, and again, less mistake, and needed less people do to the job and their people can focus on other more important work

all those things equal speed and quality at the end, but I don't know how to phrase those as they are usually the key selling points for line of business operations from my experience.

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
Is it normal that the first link is empty: [off-the-shelf APIs]()

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
**you don't have to write any code to use our data extraction APIs** is true, but most people won't use our product in the browser, so I would focus on , don't have to create your own data model, and train it maybe?

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
**Although, this can be used only in the browser** is not true!!! The goal of all of our API is that they can easily be use in your code: this is why we have the SDKs.

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
Passport is one we want to promote less compared to the two others that cover a lot of customers needs, so

[Passport OCR API](https://developers.mindee.com/docs/passport-ocr), [Receipt OCR API](https://developers.mindee.com/docs/receipt-ocr), [Invoice OCR API](https://developers.mindee.com/docs/invoice-ocr), etc.

I would usually ask them to be in order, but at least, they should be Invoice, Receipts, Passport...

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
In addition to the fact that we trained them, I would add something about the fact we created the data model. As simple as it sounds for a receipts (date, taxes, total...), creating quality data models (right fields, best data type...) is what our customers struggle the most with.

I liked what I wrote in my PR: We meticulously crafted the data model specific to each of these use cases.

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +## Mindee's Products
I think the products should be headers: putting them in a simple unordered list make them feel less important IMNSHO

2022-01-07 21:53 UTC, fharper commented on get-started/what-is-mindee.md
> +3. **Document classification**: Sometimes, you need to classify documents automatically in your code. One reason can be that you want to make your users' life easier, and let them upload several diff
**Not anymore with the API builder** is missing a coma after anymore no?

2022-01-07 21:56 UTC, fharper commented
> I think I go we the latter, I added a space for the link which I would add once the page is created. Also, the other information for the off-the-shelf API that i didn't include would be added to that page.

I'm fine with having the geography that is associated with some ots (my new acronym for off-the-shelf) apis, but I still think we should all list them in the intro to Mindee documentation. The marketing website doesn't do a good job to highlight them, and most developer will jump directly to the doc to evaluate us vs reading the product page on the site. Obviously, it may not be needed once we'll have all of them with their own page in the documentation as you'll easily see them in the left menu. I'm fine if you don't agree at all with me, don't put them :)

2022-01-07 22:32 UTC, fharper commented on get-started/what-is-mindee.md
> +- **docTR**: [Document Text Recognition](https://github.com/mindee/doctr) is a seamless, high-performing, and easily accessible library for OCR-related tasks powered by Deep Learning.
I know it sounds weird, but I wouldn't put it there. It's an introduction to Mindee, our paying product. We decided to have limited promotion of docTR on our website since it's kinda competing against our paid product for some common needs 😬

2022-01-08 00:10 UTC, fakela commented on get-started/what-is-mindee.md
> +title: Welcome to Mindee Documentation
When I search Mindee documentation no form of documentation shows so I put that maybe it might make a difference. Also, its the first page so welcoming users to the documentation is nice

2022-01-08 00:14 UTC, fakela commented on get-started/what-is-mindee.md
> + - Due date
i remember doing this guess i didn't commit it then

2022-01-08 00:18 UTC, fakela commented on get-started/what-is-mindee.md
> +[Mindee](https://mindee.com) is an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer using computer vision and machine learning.
okay

2022-01-08 00:19 UTC, fakela commented on get-started/what-is-mindee.md
> +## Key Concepts
i have already removed it. I'm no longer seeing it on my end

2022-01-08 00:29 UTC, fakela commented on get-started/what-is-mindee.md
> +Our mission is to help developers automate paperwork in their applications in real-time, with human-level accuracy.
I was trying to align what was on our website to the docs. Merging the two together: Our mission is to provide real-time, human-level accuracy in data extraction from paper and digital documents for our customers

2022-01-08 00:32 UTC, fakela commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
I kinda hinted it that I will add that once I create off-the-shelf APIs page

2022-01-08 02:23 UTC, fakela commented on get-started/what-is-mindee.md
> +## Mindee's Products
H3 headers I suppose

2022-01-10 16:55 UTC, fakela commented on get-started/what-is-mindee.md
> +[Mindee](https://mindee.com) is an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer using computer vision and machine learning.
Here is a rephrased sentence: _Mindee is a powerful OCR software and an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer through data recognition for key information using computer vision and machine learning. In addition to easily detecting and extracting key information using our pre-trained data models for common documents (e.g., invoices, receipts, passports, etc.), developers can easily build their own document parsing API, thereby enabling any type of business to solve all document-based use cases quickly and easily._

2022-01-10 17:03 UTC, fakela commented on get-started/what-is-mindee.md
> +[Mindee](https://mindee.com) is an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer using computer vision and machine learning.
left follow up comment up

2022-01-10 17:31 UTC, fakela commented on get-started/what-is-mindee.md
> +Mindee has a developer-first mindset and aims to build powerful document parsing APIs that developers can utilize to solve their problems. Mindee can be used if you are:
so here is a rephrase: 
Mindee has a developer-first mindset and strives to provide robust document parsing APIs that developers may use to solve their issues. Mindee eliminates the need for human data entry. This results in:
- increased efficiency
- fewer errors during data extraction, and
- It enables individuals to concentrate on more essential tasks.

Mindee can be used if you are:
- dealing with a lot of documents that aren't very organized, like invoices, receipts, forms, and so on.
- need high-quality data extracted.
- need data to be retrieved quickly.

2022-01-10 17:35 UTC, fakela commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
okay

2022-01-10 17:36 UTC, fakela commented on get-started/what-is-mindee.md
> +- **docTR**: [Document Text Recognition](https://github.com/mindee/doctr) is a seamless, high-performing, and easily accessible library for OCR-related tasks powered by Deep Learning.
understood

2022-01-10 18:58 UTC, fharper commented on get-started/what-is-mindee.md
> +title: Welcome to Mindee Documentation
ok

2022-01-10 18:59 UTC, fharper commented on get-started/what-is-mindee.md
> +## Key Concepts
ok, I'll check when it will be ready for the next review :)

2022-01-10 18:59 UTC, fharper commented on get-started/what-is-mindee.md
> +Our mission is to help developers automate paperwork in their applications in real-time, with human-level accuracy.
Perfect! Never take the website as an example, it needs a lot of changes 😬

2022-01-10 19:00 UTC, fharper commented on get-started/what-is-mindee.md
> +[Mindee](https://mindee.com) is an API-first platform that helps developers automate applications' workflows by standardizing the document processing layer using computer vision and machine learning.
LGTM

2022-01-10 19:01 UTC, fharper commented on get-started/what-is-mindee.md
> +Mindee has a developer-first mindset and aims to build powerful document parsing APIs that developers can utilize to solve their problems. Mindee can be used if you are:
Love it

2022-01-10 19:02 UTC, fharper commented on get-started/what-is-mindee.md
> +- **Off-the-shelf APIs**: With [off-the-shelf APIs](), you don't have to write any code to use our data extraction APIs. Although, this can be used only in the browser, each of our off-the-shelf APIs
It won't validate when I'll add a markdown linter so you can add the link once there is an actual link: it's not time saving anyway :)

2022-01-10 19:03 UTC, fharper commented on get-started/what-is-mindee.md
> +## Mindee's Products
Yep, always one header after the containing header.

2022-01-11 21:28 UTC, fharper approved these changes
LGTM

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +- increased efficiency
This list here use no end punctuation, and is read as a sentence cut in three as the list right under use a different format (dot at end of each sentences). I would assume consistency unless it's intended? In that case, I would love to learn why please.

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +Mindee can be used if you are:
Should we be clear that those are examples and not just a complete lists of reasons to use Mindee?

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +- [Passport OCR API](https://developers.mindee.com/docs/passport-ocr). Feel free to ask us about our roadmap to see what is coming next.
Remove the feel free to ask

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +Our off-the-shelf APIs are ready-to-use data extraction solutions: it is as easy as calling the API for the specific document you want to get information from. We meticulously crafted the data model
Can we add that those are the ones available NOW but that we are working on new ones, without being specific in terms of deadline or what are those

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +[Mindee API Builder](https://mindee.com/lp/ocr-document-learning) is our battle-tested deep learning OCR algorithm that allows users to design and train an API to extract the data they need from any
I would point to https://developers.mindee.com/docs/build-your-first-document-parsing-api instead, and explaining a bit better what is it in that page instead of jumping right in the tutorial. As a rule of thumb, I wouldn't point to the website for now.

2022-01-11 21:28 UTC, fharper commented on get-started/what-is-mindee.md
> +## What Mindee Offers
Shouldn't that go before listing our products?

2022-01-11 21:28 UTC, merged

2022-01-11 21:49 UTC, fakela commented on get-started/what-is-mindee.md
> +- increased efficiency
@fharper There was a reason as I punctuated only the final list item. It was like a continuous sentence but i wanted the reader to easily see it, hence it was in a list format. An example of something lie this can be seen here https://intelligentediting.com/blog/how-to-punctuate-bulleted-and-numbered-lists/

2022-01-11 21:53 UTC, fakela commented on get-started/what-is-mindee.md
> +[Mindee API Builder](https://mindee.com/lp/ocr-document-learning) is our battle-tested deep learning OCR algorithm that allows users to design and train an API to extract the data they need from any
That page will  have to be updated

2022-01-11 21:54 UTC, fakela commented on get-started/what-is-mindee.md
> +## What Mindee Offers
let me rearrange and see