update invoice ocr
mindee/documentation pull request #19
Opened 2022-01-03 14:36 UTC by fakela

2022-01-03 19:26 UTC, fharper requested changes
Some small changes needed

2022-01-03 19:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +In a few seconds, the API extracts a set of data such as: total amount including taxes, invoice number, invoice date, due date, supplier name, supplier identification number (SIRET, EIN, VAT number..
Maybe put them in a unordered list in ASC

2022-01-03 19:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +1. Log into your Mindee account and access your Invoice API environment by clicking the **Invoice API card**:
environment = dashboard

2022-01-03 19:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +2.  You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change).  On the left navigation, there are links to “Documentation”, “API Keys” an
...will change).  On

there is a double space

2022-01-03 19:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +2.  You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change).  On the left navigation, there are links to “Documentation”, “API Keys” an
Another double space

...Interface”.  The docs

2022-01-03 19:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +Rather than try out the demo, we want to build with the API, click on **API Keys** to create an API key.
I don't understand the "Rather than try out the demo" part?

2022-01-03 20:27 UTC, fakela commented on tutorials/invoice-ocr.md
> +2.  You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change).  On the left navigation, there are links to “Documentation”, “API Keys” an
🤦‍♀️ 🤦‍♀️

2022-01-03 20:30 UTC, fakela commented on tutorials/invoice-ocr.md
> +Rather than try out the demo, we want to build with the API, click on **API Keys** to create an API key.
Change that to life interface

2022-01-03 20:31 UTC, fakela commented on tutorials/invoice-ocr.md
> +In a few seconds, the API extracts a set of data such as: total amount including taxes, invoice number, invoice date, due date, supplier name, supplier identification number (SIRET, EIN, VAT number..
👍👍

2022-01-03 21:42 UTC, fakela commented
Found some additional tweaks to make, after I requested for a review 🤦‍♀️.

2022-01-03 23:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +- invoice date
i should be a capital letter

2022-01-03 23:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +It takes the API a few seconds to extract data from your PDFs or photos of invoices. The API extracts data such as:
You missed my comment on listing them in ASC order :)

2022-01-03 23:26 UTC, fharper commented on tutorials/invoice-ocr.md
> +1. Log into your Mindee account and access your Invoice API environment by clicking the **Invoice API card**:
And it's also the name of the environment :)

2022-01-03 23:29 UTC, fharper requested changes
See new comments

2022-01-03 23:29 UTC, fharper commented on tutorials/invoice-ocr.md
> +2. You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change). On the left navigation, there are links to “Documentation”, “API Keys” and
_Rather than try out the Live Interface, we will build with the API_

The Live Interface use the API, so I would say something like: Rather than try out the Live Interface, we will make an API call manually using the Terminal.

or something like that

2022-01-04 07:18 UTC, fakela commented on tutorials/invoice-ocr.md
> +2. You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change). On the left navigation, there are links to “Documentation”, “API Keys” and
saying _terminal_ might be a bit confusing as we are not using that term in the docs,  for final it will look like this:  _Rather than try out the Live Interface, we will make an API call manually._

2022-01-04 07:26 UTC, fakela commented on tutorials/invoice-ocr.md
> +It takes the API a few seconds to extract data from your PDFs or photos of invoices. The API extracts data such as:
Done ✅

2022-01-04 20:06 UTC, fharper commented on tutorials/invoice-ocr.md
> +2. You'll land on the dashboard page - where you can quickly see API usage (you have none right now, but that will change). On the left navigation, there are links to “Documentation”, “API Keys” and
LGTM!

2022-01-04 20:08 UTC, fharper approved these changes
LGTM

2022-01-04 20:08 UTC, merged