Review Setting up your account page
mindee/documentation pull request #199
Opened 2022-01-07 10:06 UTC by fakela

Review Setting up your account page #135

2022-01-07 22:25 UTC, fharper requested changes
We want our documentation to be the most complete possible, which means sometimes taking the user by the hand as I don't want us to assume they know how to do things, even simple daily things we do. It's also important to pay attention to details for any documentation IMNSHO :)

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +  description: 'setup your account on Mindee'
Don't add description there as discussed in https://github.com/mindee/documentation/issues/198

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  1. Go to the [Signup page](https://platform.mindee.com).
The sign-up link is https://platform.mindee.com/signup

when you go to https://platform.mindee.com, by default, it's the login page

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  2. Enter your username, email address, and password in the right fields.
**Enter your username** = the desired username since they don't have any yet

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  3.  Check the box to agree to the "Terms of Use".
Once you read the terms of use, check...

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  3.  Check the box to agree to the "Terms of Use".
Also, check the first box

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  ---
In this page, should we use the term checkbox instead of box for the... checkbox?

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> + > Optional: Check the other box to receive news about Mindee.
I would sell a bit better the newsletter, something like:

Check the other checkbox to subscribe to our monthly newsletter.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +4. Click on **Sign Up**.
... to create your account

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  5. Check your email for confirmation and follow the instructions in the email to activate your account.
Maybe we should add something about being sure to check the spam box (not that it goes there, but it is written of mostly all sites since it's a possibility), and to whitelist our email? Or maybe just the check the spam box...

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +![A screenshot of the signup page](https://files.readme.io/c4c9f92-signup.png "Create an account in Mindee")
Can we update the screenshot so it's symetric

![CleanShot 2022-01-07 at 17 08 41@2x](https://user-images.githubusercontent.com/1170989/148613860-266ba454-6076-4a04-9897-bbba9a18d80d.png)

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +![A screenshot of the signup page](https://files.readme.io/c4c9f92-signup.png "Create an account in Mindee")
The ALT description should contain a lot more information. If I can't see the image, I don't know what the sign up page looks like. The goal of the ALT text is to give somewhat the same experience that you would have seeing the image.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +![A screenshot of the single sign-on in Mindee](https://files.readme.io/c44333f-Screenshot_2021-11-22_at_23.49.32.png "Sign in with Github or Google")
Same comment as the previous ALT text

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +![A screenshot of the single sign-on in Mindee](https://files.readme.io/c44333f-Screenshot_2021-11-22_at_23.49.32.png "Sign in with Github or Google")
Same comment for image symmetry as the previous one

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +## Single sign-on
We need to show an example on how it's working for each SSO provider.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  1. Go to the [Login](https://platform.mindee.com) page.
Maybe put this link https://platform.mindee.com/login just in case that https://platform.mindee.com/ is something else in the future or default to something else.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
>  > If you forgot your password, click the link "password forgotten" and follow the instructions. You will be sent an email. Check your spam if you don't receive any email.
I would create a section in this page just about that, and show how it's working step by step

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +5. Alternatively, you can log in with your Github or Google account.
Let's show step by step how it's working.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +4. Click on **Log in**.
The steps goes from 2 to 4

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +![A screenshot of the login page](https://files.readme.io/391d480-Screenshot_2021-11-22_at_19.49.34.png "Login to Mindee")
Same comments as previous images

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +## Subscribe to an API
I wonder if this should be in the setup account, as it's not about setuping your account, but about using an API. Yeah, I would be that in the next page, and maybe some of this won't be needed.

2022-01-07 22:25 UTC, fharper commented on get-started/setup-your-account.md
> +## Subscribe to an API
I'll review the rest once it's moved in the other page or if for whatever reason we decide to leave it in this page.

2022-01-08 01:12 UTC, fakela commented on get-started/setup-your-account.md
>  2. Enter your username, email address, and password in the right fields.
The first one works but to make it more specific we can add that

2022-01-08 01:13 UTC, fakela commented on get-started/setup-your-account.md
>  ---
i will have to rephrase it

2022-01-08 01:19 UTC, fakela commented on get-started/setup-your-account.md
> +4. Click on **Sign Up**.
I wouldn't add this here, it’s already indicated at the top what the steps is for

2022-01-08 01:20 UTC, fakela commented on get-started/setup-your-account.md
>  5. Check your email for confirmation and follow the instructions in the email to activate your account.
This should do the trick:  Check your email or spam box for confirmation and follow the instructions in the email to activate your account.

2022-01-08 01:21 UTC, fakela commented on get-started/setup-your-account.md
> +![A screenshot of the signup page](https://files.readme.io/c4c9f92-signup.png "Create an account in Mindee")
okay sure

2022-01-08 01:39 UTC, fakela commented on get-started/setup-your-account.md
> +![A screenshot of the signup page](https://files.readme.io/c4c9f92-signup.png "Create an account in Mindee")
I actually don’t want the ALT to be very long sentences. It should be eye-catching and descriptive enough.  

What do you think about this: _signup page with fields to fill to create an account_

2022-01-08 01:40 UTC, fakela commented on get-started/setup-your-account.md
> +## Single sign-on
Okay 👌 , I will add more written context for that

2022-01-08 01:41 UTC, fakela commented on get-started/setup-your-account.md
>  > If you forgot your password, click the link "password forgotten" and follow the instructions. You will be sent an email. Check your spam if you don't receive any email.
Make sense

2022-01-08 01:42 UTC, fakela commented on get-started/setup-your-account.md
> +5. Alternatively, you can log in with your Github or Google account.
okay

2022-01-08 01:43 UTC, fakela commented on get-started/setup-your-account.md
> +## Subscribe to an API
I don’t think it should be here cause it's explained in the next page. Would remove it.

2022-01-12 21:02 UTC, fharper approved these changes
@fakela remove the Markdown Comments and merge this for now as it's impossible to follow up the reviews. I think at this point, the things left to do are mostly updating the images correctly.

2022-01-12 21:15 UTC, merged