Create mindee-glossary.md
mindee/documentation pull request #202
Opened 2022-01-07 19:30 UTC by fakela

Would need more ideas and definition of terminologies used in Mindee

2022-01-07 22:25 UTC, fharper commented
It's fine if we start small, we'll build the glossary while revising the documentation

2022-01-11 21:37 UTC, fharper commented
@fakela: we can add something about: if you think a term should be explained, please let us know on Slack. And maybe something about the fact that this page is a work in progress, so it doesn't look too empty, but we could merge it now so it is already profitable for our actual users, WDYT?

2022-01-12 21:16 UTC, fakela commented
> @fakela: we can add something about: if you think a term should be explained, please let us know on Slack. And maybe something about the fact that this page is a work in progress, so it doesn't look too empty, but we could merge it now so it is already profitable for our actual users, WDYT?

Yes, we can. I will share this tomorrow on slack too

2022-01-19 17:12 UTC, fharper reviewed
Should we add something about the fact that it's a work in progress, or that we will continually add terms in it? Since it's a bit empty for now.

2022-01-19 17:12 UTC, fharper requested changes

2022-01-19 17:12 UTC, fharper commented on get-started/mindee-glossary.md
> +- **Models**: A model is a machine learning file that can be trained to carry out specific tasks such as extracting the total amount info from receipts etc.
Alphabetical order :)

2022-01-24 21:37 UTC, fharper approved these changes
LGTM

2022-01-24 21:37 UTC, merged