Review prediction.md
mindee/documentation pull request #221
Opened 2022-01-13 18:39 UTC by fakela

2022-01-27 13:51 UTC, fakela commented
This it the documentation that Emmanuelle provided the Google Doc for

2022-01-27 22:36 UTC, fharper requested changes

2022-01-27 22:36 UTC, fharper commented on apis-overview/endpoints/prediction.md
> + "document": {
I don't understand why this response is there?

2022-01-27 22:36 UTC, fharper commented on apis-overview/endpoints/prediction.md
> + "document": {
Oh, I think I get it, but I feel it's confusing since we are showing examples of each prediction level right after

2022-01-27 22:36 UTC, fharper commented on apis-overview/endpoints/prediction.md
> +!!! success "Prediction structure"
Are the `!!!` a special README.io syntax?

2022-01-27 22:38 UTC, fharper commented
I added some questions, and comments on things we need to update before merging this PR. I added the non-urgent comments, questions or changes to be made after me merge this PR on #242

2022-01-27 22:49 UTC, fakela commented on apis-overview/endpoints/prediction.md
> +    Minor versions are only available for custom APIs built using the API builder while major versions are available for both off-the-shelf and custom APIs. When       using the API builder, each tra
It's because of the syntax `!!!`

I saw online that it's a way to write a callout block.

2022-01-27 22:50 UTC, fakela commented on apis-overview/endpoints/prediction.md
> +  -d '{"document": "https://my_file.pdf"}'
what will the write one be

2022-01-27 23:33 UTC, fakela commented
@fharper ready to be merged

2022-01-28 14:38 UTC, fharper commented on apis-overview/endpoints/prediction.md
> +  -d '{"document": "https://my_file.pdf"}'
Sorry wasn't clear, what I wrote is the right command.

2022-01-28 16:17 UTC, fharper reviewed
LGTM

2022-01-28 16:18 UTC, fharper approved these changes

2022-01-28 16:18 UTC, merged

2022-01-28 16:19 UTC, fharper commented
@fakela: can you now prioritize the changes from #242 so we can put this page as complete :)