Review endpoints documentation
mindee/documentation pull request #225
Opened 2022-01-14 10:28 UTC by fakela

Review endpoints documentation #139

2022-01-19 17:09 UTC, fharper requested changes

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +Mindee provides several document extraction APIs, whether off-the-shelf or trainable by the user. To make a prediction or train an API, we use a REST interface where you can make requests over HTTP p
HTTPS not HTTP

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +Mindee provides several document extraction APIs, whether off-the-shelf or trainable by the user. To make a prediction or train an API, we use a REST interface where you can make requests over HTTP p
I would also add `https://`on URLs so it's even clearer.

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +- **__<account_name>__**: is your user name or organization name.
Shouldn't `user name` be `username`?

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +- **__<account_name>__**: is your user name or organization name.
Should we add a little info box about where to find this information?

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +- **__<api_name>__**: the name of your document extraction API.
Should we add a little info box about where to find this information?

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +Each request made to the REST API must be authenticated with an API key generated through Mindee. The API key is specific to the document parsing API you are working with.
We alternate between `document parsing`and `document extraction` API in the documentation. Shouldn't we stick to one term?

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +```
when moving from a README.io block to a Markdown code block, you also need to remove the

```
{
  "codes": [
    {
      "code":
```

in the beginning, and

```
  ]
}
```

at the bottom. Also, reindent correctly the code while changing `\n` for real line breaks, and removing the escape character in front of the double-quotes.

2022-01-19 17:09 UTC, fharper commented on apis-overview/endpoints.md
> +The other JSON keys depend on the resource you want to access, this is where you will find information about what happened during your request. See [Prediction JSON response](https://developers.minde
Should we link in this sentence "this is where you will find information about what happened during your request" instead of having an additional see... Not being picky, but the "this is where" makes me think it should point to something :)

2022-01-19 17:12 UTC, fakela commented on apis-overview/endpoints.md
> +- **__<api_name>__**: the name of your document extraction API.
Okay, where can we find it . I can ask on slack

2022-01-19 17:16 UTC, fakela commented on apis-overview/endpoints.md
> +The other JSON keys depend on the resource you want to access, this is where you will find information about what happened during your request. See [Prediction JSON response](https://developers.minde
Good point

2022-01-19 20:02 UTC, fharper commented on apis-overview/endpoints.md
> +Each request made to the REST API must be authenticated with an API key generated through Mindee. The API key is specific to the document parsing API you are working with.
Maybe "Mindee API" so it's not confusing and we already explain what they do in the intro?

2022-01-19 20:05 UTC, fharper commented on apis-overview/endpoints.md
> +- **__<api_name>__**: the name of your document extraction API.
Username is available at https://platform.mindee.com/apishub/account?setup=default
API name is available in the settings page of your API dashboard (or at the top left of that page or on the API list in your API Hub)

2022-01-24 21:47 UTC, fharper approved these changes
LGTM

2022-01-24 21:47 UTC, merged