review error-management.md
mindee/documentation pull request #226
Opened 2022-01-14 11:58 UTC by fakela

2022-01-17 22:18 UTC, fharper requested changes

2022-01-17 22:18 UTC, fharper commented on apis-overview/error-management.md
> +      "code": "{\n  \"api_request\": \n  {\n    \"error\": {}, \n    \"resources\": [\"document\"], \n    \"status\": \"success\", \n    \"status_code\": 201, \n    \"url\": \"https://api.mindee.net/
\n = real break line
\" = no need to escape in markdown code

it will make the code more readable in the markdown file

2022-01-17 22:18 UTC, fharper commented on apis-overview/error-management.md
> +  "codes": [
\n = real break line
\" = no need to escape in markdown code

it will make the code more readable in the markdown file

2022-01-17 22:41 UTC, fakela commented on apis-overview/error-management.md
> +      "code": "{\n  \"api_request\": \n  {\n    \"error\": {}, \n    \"resources\": [\"document\"], \n    \"status\": \"success\", \n    \"status_code\": 201, \n    \"url\": \"https://api.mindee.net/
should i remove the line breaks ` /n`

2022-01-19 16:58 UTC, fharper approved these changes
LGTM

2022-01-19 16:58 UTC, fharper commented on apis-overview/error-management.md
> +  "api_request":
Why is the JSON different?

2022-01-19 16:58 UTC, fharper commented on apis-overview/error-management.md
> +  "api_request":
My bad!

2022-01-19 17:00 UTC, merged