Add info on where api, account and version can be found
mindee/documentation pull request #245
Opened 2022-01-28 17:38 UTC by fakela

2022-02-01 20:05 UTC, fharper requested changes

2022-02-01 20:05 UTC, fharper commented on apis-overview/endpoints/prediction.md
> +- **account_name**: refers to the username or organization name of the account that created the API. For the off-the-shelf APIs, this will read as 'mindee'. This can be found at the top right of the
Which page?

2022-02-01 20:06 UTC, fakela commented on apis-overview/endpoints/prediction.md
> +- **account_name**: refers to the username or organization name of the account that created the API. For the off-the-shelf APIs, this will read as 'mindee'. This can be found at the top right of the
screen should be a better way to describe it.

2022-02-01 20:14 UTC, fharper commented on apis-overview/endpoints/prediction.md
> +- **account_name**: refers to the username or organization name of the account that created the API. For the off-the-shelf APIs, this will read as 'mindee'. This can be found at the top right of the
Still, which screen? Unless I'm mistaken, when the user read this page, it's not about being in any specific page, it's information about using the prediction endpoint no?

2022-02-01 22:25 UTC, fakela commented on apis-overview/endpoints/prediction.md
> +- **account_name**: refers to the username or organization name of the account that created the API. For the off-the-shelf APIs, this will read as 'mindee'. This can be found at the top right of the
In the suggestion, you mentioned adding the information like I did on this page
https://developers.mindee.com/docs/endpoints
But this API is generated so I think that information is necessary.

2022-02-02 21:16 UTC, fharper approved these changes
LGTM

2022-02-02 21:16 UTC, merged