update document-input page by adding suggestions
mindee/documentation pull request #251
Opened 2022-01-31 22:45 UTC by fakela

update document-input page by adding suggestions from #249

2022-02-01 19:58 UTC, fharper requested changes

2022-02-01 19:58 UTC, fharper commented on apis-overview/document-inputs.md
> +- **Using the cutPdf Library**: The cutPDF library is available when using the SDK. This library is used when sending multi pages pdf of more than 5 pages.
`cutPDF` isn't a librairy, it's an option in the SDKs

2022-02-01 19:58 UTC, fharper commented on apis-overview/document-inputs.md
> +> Always choose images over PDF for scans and photos (as images are processed faster).
When possible, send images over...


Also, let's add something about the fact that the photos or PDF work just fine, they aren't just AS fast.

2022-02-01 19:58 UTC, fharper commented on apis-overview/document-inputs.md
> +> Always choose images over PDF for scans and photos (as images are processed faster).
Actually, let's say something more like "If you want faster process time..."

2022-02-01 20:05 UTC, fakela commented on apis-overview/document-inputs.md
> +- **Using the cutPdf Library**: The cutPDF library is available when using the SDK. This library is used when sending multi pages pdf of more than 5 pages.
I saw this library thing in the docs and thought it was a library

2022-02-01 20:13 UTC, fharper commented on apis-overview/document-inputs.md
> +- **Using the cutPdf Library**: The cutPDF library is available when using the SDK. This library is used when sending multi pages pdf of more than 5 pages.
Where? We should fix it if it's not clear.

2022-02-02 07:20 UTC, fakela commented on apis-overview/document-inputs.md
> +- **Using the cutPdf Library**: The cutPDF library is available when using the SDK. This library is used when sending multi pages pdf of more than 5 pages.
https://developers.mindee.com/docs/nodejs-invoice-ocr

2022-02-02 21:12 UTC, fharper approved these changes
LGTM

2022-02-02 21:13 UTC, merged