Changes for Python SDK v2
mindee/documentation pull request #274
Opened 2022-02-08 07:53 UTC by ianardee

Update documentation for the Python SDK v2.

2022-02-08 12:39 UTC, fharper requested changes

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk.md
> +> [Getting started](doc:getting-started)
Let's put the full URL (you didn't know, but it's another README.IO thing only we are moving away.

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +First clone this repo:
this=the

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +you can have all your documents configured in the same client.
**Y**ou

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +requirements as well.
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +you can simply chain all the calls together:
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +handled in different ways.
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +in keeping with the example above:
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +return an object you can then serialize to the API.
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +A base64 encoded string.\
Trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +Raw bytes.\
Trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +when using FastAPI `UploadFile` objects:
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +Financial, mixed data flow of invoices and receipts.\
trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +`document_type`\
trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +`singular_name`\
trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +`plural_name`\
trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +`account_name`\
trailing backslash

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +Where `<username>` and `<document_type>` are uppercase, any `-` replaced with `_`.
Why the break line?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +Where `<username>` and `<document_type>` are uppercase, any `-` replaced with `_`.
This is not clear, can you details the example below

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +The call to the `parse` method is the same as with Off-the-Shelf documents.
documents=APIs

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-cli.md
> +The CLI tool is provided mainly for quick tests and debugging.
Should we add something like "do not use in production"?

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +### Single Document
Single Documents Type

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +### Multiple Documents
Multiple Documents Types

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +### Environment Variables
We should put back the part where we say that we highly suggest that they do that instead of having keys in their code, for security reasons.

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/python-api-builder.md
> +#### Environment Variables
We should put back the part where we say that we highly suggest that they do that instead of having keys in their code, for security reasons.

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +You **are** using environment variables in production, right?
I hear you, but let's not shame the people who don't do it :)

Or we can write it in a more friendly way like "We highly suggest to use environment variables for the API keys, if not on you development machine, at a minimum in prod"

2022-02-08 12:39 UTC, fharper commented on integration/python-sdk/getting-started.md
> +### Single Document
I understand what you did by giving three different ways for people to use the client: one document type, multiple or a mix and match. If I read that, I'm like, it's complicated to use this SDK. So maybe I would limit to one example with multiple documents type, while mentioning they can use only the code they need for the document type they need, or create ,multiple clients depending on their needs.

2022-02-08 13:41 UTC, ianardee commented on integration/python-sdk/getting-started.md
> +requirements as well.
To keep line length down. I usually keep it at around 88 chars, always under 120 chars.

https://baymard.com/blog/line-length-readability

2022-02-08 13:43 UTC, ianardee commented on integration/python-sdk/getting-started.md
> +You can also set the API keys as environment variables.\
It's supposed to make a line break `<br>` instead of a new paragraph `</p><p>`.

Like\
This

instead of

This

2022-02-08 14:22 UTC, fharper commented on integration/python-sdk/getting-started.md
> +requirements as well.
I do column 80 for code, but not for markdown that are basically documentation. It's not readable friendly :)

2022-02-14 13:32 UTC, ianardee commented on integration/python-sdk/python-cli.md
> +```
it's there

2022-02-14 13:33 UTC, ianardee commented on integration/python-sdk/python-cli.md
> +The CLI tool is provided mainly for quick tests and debugging.
No, it's useful in production for debugging.

2022-02-17 12:32 UTC, merged