Review text doc
mindee/documentation pull request #290
Opened 2022-02-17 12:42 UTC by fakela

2022-03-15 22:09 UTC, fharper requested changes
See comment in Slack :)

2022-03-21 16:06 UTC, fharper requested changes

2022-03-21 17:44 UTC, fakela commented on build-your-first-document-parsing-api/data-model-configuration/text.md
> +**Note**: The **API Response Key** is automatically filled for you but you can change that to something most suitable for you according to your needs.
Would you prefer this : _The **API Response Key** is already filled in for you, but you can change it to something that better fits your needs._

2022-03-21 18:03 UTC, fharper commented on build-your-first-document-parsing-api/data-model-configuration/text.md
> +**Note**: The **API Response Key** is automatically filled for you but you can change that to something most suitable for you according to your needs.
Oh no, it make sense, my brain was probably not there when I read it, sorry!

2022-03-21 18:03 UTC, merged