Create cropper documentation
mindee/documentation pull request #322
Opened 2022-02-23 15:56 UTC by fakela

2022-02-23 19:24 UTC, fakela commented
@fharper I made some last-minute changes.

2022-02-23 20:40 UTC, fharper requested changes

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +Mindee API prediction endpoint works with one document per request (image or PDF file). The cropper results are at the page level and each page can detect several _documents_. Most of the time, takin
I don't understand "The cropper results are at the page level and each page can detect several _documents_."

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +Mindee API prediction endpoint works with one document per request (image or PDF file). The cropper results are at the page level and each page can detect several _documents_. Most of the time, takin
for any use case = for most use case

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +## How it works
Don't we use capital letters in header?

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +### Example with receipts V3
Don't we use capital letters in header?

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +The cropper feature can be used on any API from Mindee API V1 on the prediction route:
I think we can remove the "from Mindee API V1"

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +The cropper results are stored as follows
are returned as follows in the JSON object

or something in those lines

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +In our POST request, the cropper additional param `?cropper=true` is added to the receipts V3 API from Mindee API V1.
You should add the document you use to make this example.

2022-02-23 20:40 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +```
We may want to add the initial example document with the polygon vertices highlighted, so it's more visual.

2022-02-23 21:14 UTC, fakela commented on apis-overview/endpoints/cropper.md
> +POST `https://api.mindee.net/v1/products/mindee/expense_receipts/v3/predict?cropper=true`
I can try for curl but we will have to test its accuracy

2022-02-23 22:57 UTC, fakela commented on apis-overview/endpoints/cropper.md
> +```
I don’t understand this one

2022-02-24 14:36 UTC, fharper commented on apis-overview/endpoints/cropper.md
> +```
I wanted to show something like the document with the polygons of the cropper shown on it, so people see what they get, but it's not urgent, and I'll do it as I really want to finally use our Computer Vision SDK :)

2022-02-24 14:44 UTC, fharper approved these changes
LGTM

2022-02-24 14:44 UTC, merged