add invoice v3 field
mindee/documentation pull request #365
Opened 2022-03-09 01:39 UTC by fharper

2022-03-09 12:59 UTC, fakela commented
@EmmanuelleThomas and @jonathanMindee  please can this PR be reviewed

2022-03-10 14:55 UTC, EmmanuelleThomas requested changes

2022-03-10 14:55 UTC, EmmanuelleThomas commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
for invoice it should be a .pdf

2022-03-10 14:55 UTC, EmmanuelleThomas commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +  value: '99, Duperné 75011 Paris',
this does not match with the invoice provided above

2022-03-10 14:55 UTC, EmmanuelleThomas commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
this fake invoice lacks data on customer company registration, we would need that in order to be exhaustive with our sample codes

2022-03-10 15:08 UTC, jonathanMindee requested changes
We are displaying an IBAN in the documentation on the PaymentDetails section. Can we make it obfuscated please?

Can we in general never display any information of this type? It's always better to add "****" instead of the real characters to show users that we care about keeping sensitive data private. 

Thanks :)

2022-03-10 15:08 UTC, jonathanMindee commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +- **invoice.customerCompanyRegistration** (string): customer company registration information.
Can we add as many details as there are on the SUpplier info please?

https://developers.mindee.com/docs/python-invoice-ocr

It should be added in the python Invoice SDK documentation also. I did it only for the Supplier information but basically, each object returned in the supplierCompanyRegistration list has exactly the same structure as the customerCompanyRegistration.

2022-03-10 15:48 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +### Customer Information
> could we list field in Customer and Supplier info in the same order: Name / Address / Company Registration

You want them exactly "Name / Address / Company Registration" or just the same order? For making it easier to find, we usually put them in ASC order like "Address / Company Registration / Name" which we may have missed here.

> could we change "Supplier Informations" to "Supplier Information" for consistency please?

could the consistency be the other way around, and change `Customer Information` to `Customer Informations` since they both have more than one items?

2022-03-10 15:50 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Field {
We know. Unfortunately, e don't have an invoice with all extracted fields that we can use publicly, so we create the examples with more than one invoice. So the solution is in my todo: I need to create a fake invoice with all the fields we extract, and we will update all the examples once we have it.

If you prefer, we can show example with no data. Or we can wait for that fake invoice to be created to update the documentation. Or maybe you have an invoice with all the fields that can be use publicaly?

2022-03-10 15:51 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
> when downloaded the file name should look like 'invoice.pdf'

We cannot decide of the file name. README.IO add an UUID at the beginning of the file.

2022-03-10 15:51 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
> for invoice it should be a .pdf

Why? We support JPEG also.

2022-03-10 15:52 UTC, jonathanMindee commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Field {
Hard one indeed. I had to add a company id for the supplier on the Public live interface, but hard to do the same for payment details etc..

Plus we have validation rules that prevent us from return a non valid IBAn for instance. Mohamed told me they were real Fake IBAN though, when we want to do a full sample we should see with the R&D firtst

2022-03-10 15:52 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
> this fake invoice lacks data on customer company registration, we would need that in order to be exhaustive with our sample codes

Yep, see previous comment on NOT having any invoice will all fields. As mentioned, I need to create a fake invoices with ALL the extracted information, and we will update the output and examples with that. We wanted to add the new fields ASAP with some examples. In this situation it's fine since this page isn't a tutorial, but a documentation of the SDK Invoice object.

2022-03-10 15:53 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +  value: '99, Duperné 75011 Paris',
See previous comment

2022-03-10 15:59 UTC, fharper commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +- **invoice.customerCompanyRegistration** (string): customer company registration information.
Sorry, I don't get this comment.

`supplierCompanyRegistration` doesn't exist.

2022-03-10 16:00 UTC, fakela commented
> We are displaying an IBAN in the documentation on the PaymentDetails section. Can we make it obfuscated please?
> 
> Can we in general never display any information of this type? It's always better to add "****" instead of the real characters to show users that we care about keeping sensitive data private.
> 
> Thanks :)

It's stated above that we are using a fake invoice for the examples. So the names and all sensitive information are fake and just for example purposes

2022-03-10 18:23 UTC, fakela commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +- **invoice.customerCompanyRegistration** (string): customer company registration information.
I think I got what he meant `supplier company number `  and `customer company registration` should have the same info.

Since both is around company number either for supplier or customer

2022-03-11 20:40 UTC, EmmanuelleThomas commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Field {
OK let's keep that way for now. We'll improve in the future once we have the fake data.

2022-03-11 20:44 UTC, EmmanuelleThomas commented on librairies/nodejs-sdk/nodejs-invoice-ocr.md
> +Depending on the field type specified, additional attributes can be extracted in the invoice object. Using the above [invoice example](https://files.readme.io/a74eaa5-c8e283b-sample_invoice.jpeg), th
I suggest we use ".pdf" for Invoices as it is closer to what customers usually experience. Not mandatory of course, can be modified in the future.

2022-03-11 20:47 UTC, fharper commented
I resolved the issues with the no match of invoice for the code and output JSON even if **they are not resolved**. I need to get Jonathan's fake invoice or create one, and while doing it, redo ALL examples, even the ones that were good as it will be done with a new invoice document.

2022-03-11 21:06 UTC, fharper commented
I changed the JPEG for a PDF, and obfuscate the fake IBAN.

2022-03-11 21:07 UTC, fharper commented
As discussed, we will merge now, and next step is to update all JSON output with a fake invoice.

2022-03-11 21:07 UTC, merged

2022-03-13 20:44 UTC, fakela commented
@fharper as usual, README is doing there thing, the changes are not reflecting